// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kdwils/envoy-proxy-bouncer/server (interfaces: Notifier)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_notifier.go -package=mocks github.com/kdwils/envoy-proxy-bouncer/server Notifier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	bouncer "github.com/kdwils/envoy-proxy-bouncer/bouncer"
	gomock "go.uber.org/mock/gomock"
)

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
	isgomock struct{}
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// NotifyCheckedRequest mocks base method.
func (m *MockNotifier) NotifyCheckedRequest(ctx context.Context, result bouncer.CheckedRequest) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyCheckedRequest", ctx, result)
}

// NotifyCheckedRequest indicates an expected call of NotifyCheckedRequest.
func (mr *MockNotifierMockRecorder) NotifyCheckedRequest(ctx, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyCheckedRequest", reflect.TypeOf((*MockNotifier)(nil).NotifyCheckedRequest), ctx, result)
}

// NotifyCaptchaVerified mocks base method.
func (m *MockNotifier) NotifyCaptchaVerified(ctx context.Context, ip string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyCaptchaVerified", ctx, ip)
}

// NotifyCaptchaVerified indicates an expected call of NotifyCaptchaVerified.
func (mr *MockNotifierMockRecorder) NotifyCaptchaVerified(ctx, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyCaptchaVerified", reflect.TypeOf((*MockNotifier)(nil).NotifyCaptchaVerified), ctx, ip)
}
