name: charts

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  charts:
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'charts/')
    uses: ./.github/workflows/helm-publish.yaml
    with:
      charts_dir: charts/envoy-proxy-bouncer
      oci_registry: ghcr.io
